data:
  train_width: 512 
  train_height: 512 
  sample_rate: 25 
  n_sample_frames: 1
  n_motion_frames: 2

training:
  frame_offset: 20
  checkpoint_path: './checkpoint_epoch50.pth'
  load_epoch: 10
  save_interval: 5
  log_interval: 5
  lambda_perceptual: 1.0
  lambda_adversarial: 1.0
  lambda_cosine: 1.0
  lambda_keypoints: 1.0
  lambda_gaze: 1.0
  lambda_supervised: 1.0
  lambda_unsupervised: 1.0
  batch_size: 1
  num_workers: 0
  lr: 1.0e-3
  base_epochs: 100
  hr_epochs: 2
  student_epochs: 2
  use_gpu_video_tensor: True
  prev_frames: 2  #number of previous frames to consider
  # video_dir:  '/home/iby_vishwa/Documents/Megaportraits/CelebV-HQ/celebvhq/35666' 
  video_dir: './short'
  sample_rate: 25  
  n_sample_frames: 100
  json_file: './data/overfit.json'
  # json_file: '/home/iby_vishwa/Documents/Megaportraits/CelebV-HQ/celebvhq_info.json'
  
  w_per: 20  # perceptual loss
  w_adv: 1   # adversarial loss
  w_fm: 40   # feature matching loss
  w_cos: 2   # cycle consistency loss
  w_pairwise: 1
  w_identity: 1
  w_cyc:  1



