# Generated by Django 4.2.13 on 2024-06-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("therapy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emotionanalysis",
            name="session_id",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="toneanalysis",
            name="session_id",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="transcription",
            name="session_id",
            field=models.CharField(default="", max_length=100),
        ),
    ]
