# Generated by Django 4.2.13 on 2024-06-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("therapy", "0002_emotionanalysis_session_id_toneanalysis_session_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="toneanalysis",
            name="features",
        ),
        migrations.AddField(
            model_name="toneanalysis",
            name="emotion",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="toneanalysis",
            name="session_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="toneanalysis",
            name="timestamp",
            field=models.FloatField(),
        ),
    ]
