# Generated by Django 4.2.13 on 2024-06-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("therapy", "0004_conversation"),
    ]

    operations = [
        migrations.CreateModel(
            name="TherapistResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100)),
                ("text", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Conversation",
        ),
        migrations.AlterField(
            model_name="emotionanalysis",
            name="session_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="emotionanalysis",
            name="timestamp",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="toneanalysis",
            name="emotion",
            field=models.CharField(default="neutral", max_length=50),
        ),
        migrations.AlterField(
            model_name="toneanalysis",
            name="session_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="transcription",
            name="session_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="transcription",
            name="timestamp",
            field=models.FloatField(),
        ),
    ]
