# Generated by Django 4.2.13 on 2024-06-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("therapy", "0005_therapistresponse_delete_conversation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="therapistresponse",
            name="session_id",
            field=models.CharField(max_length=255),
        ),
    ]
